name: build-embed
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # <<< ÖNEMLİ: push için gerekli

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: embed.html üret
        run: python build.py

      # Değişiklikleri otomatik commit + push
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update embed.html"
          file_pattern: embed.html
