name: build-embed

on:
  schedule:
    - cron: "0 * * * *"      # her saat başı
  workflow_dispatch:          # elle tetikleme

permissions:
  contents: write             # << push için şart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build embed.html
        run: python build.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update embed.html"
          file_pattern: embed.html
