name: build-embed

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # push izni

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # tüm geçmişi çek

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python build.py

      - name: Commit & push embed.html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update embed.html"
          file_pattern: embed.html
